name: config/config.yml

seeds: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009]

num_epoch: 200

path:
  load: /home/hashimoto/User/data/data
  save: result/STGraphormer
  
device:
  cuda: true
  parallel: false
  id: [2]

dataset:
  flip_pairs: [[4, 1], [5, 2], [6, 3], [10, 13], [11, 14], [12, 15]] 
  add_vel: true
  add_acc: true
  inward: [[1, 0], [2, 1], [3, 2], [4, 0], 
           [5, 4], [6, 5], [7, 0], [8, 7], 
           [9, 8], [10, 7], [11, 10], [12, 11], 
           [13, 7], [14, 13], [15, 14]]
  batch_size: 4

model:
  name: STGraphormer
  args:
    in_channels: 6
    num_class: 2
    s_nhead: 8
    t_nhead: 8
    dim_feedforward: 512
    num_layers: 2
    dropout: 0.3
    graph_args:
      num_node: 16
      inward: [[1, 0], [2, 1], [3, 2], [4, 0], 
               [5, 4], [6, 5], [7, 0], [8, 7], 
               [9, 8], [10, 7], [11, 10], [12, 11], 
               [13, 7], [14, 13], [15, 14]]
      strategy: spatial # option [uniform/distance*/distance/spatial/DAD/DLD]

optim:
  name: optim.Adam
  args:
    lr: 1.0e-5
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 1.0e-03
    amsgrad: false
    foreach: null 
    maximize: false
    capturable: false

skd:
  name: optim.lr_scheduler.MultiStepLR # if not use, define null
  args:
    milestones: [100,150,175]
    gamma: 0.1

criterion:
  name: nn.CrossEntropyLossname: config/config.yml

seeds: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009]

num_epoch: 200
